version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    
  frontend:
    build:
      context: ./frontend/LangPortal
      dockerfile: Dockerfile
    ports:
      - "8081:8090"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:8080/api

networks:
  default:
    driver: bridge