version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - langportal-network

  frontend:
    build:
      context: ./frontend/LangPortal
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - langportal-network

networks:
  langportal-network:
    driver: bridge