spring:
  datasource:
    url: jdbc:sqlite:langportal.db?foreign_keys=on
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      
server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.langportal: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE